image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      echo 'use nix' > .envrc &&
      direnv allow .
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addBadge: true
    addLabel: true
    
vscode:
  extensions:
    - bbenoist.Nix
    - PKief.material-icon-theme
    - CoenraadS.bracket-pair-colorizer
